export const CONTENT = {
	logo: 'markmelnik',
	fullname: 'Mark Melnik',
	home: {
		title: 'Home',
		header: 'About Me',
		number: '.00',
	},
	about: {
		title: 'About',
		header: 'About Me',
		number: '.01',
		p1: `Hey there! I'm Mark, a software developer based in New York City. I
		solve complex technical problems and build full-stack applications
		for the web. I am currently seeking an entry-level software development role.`,
		p2: `Check out my projects below!`,
	},
	skills: {
		title: 'Skills',
		header: `I've been working with`,
	},
	projects: {
		title: 'Projects',
		header: 'My Projects',
		number: '.02',
		button: {
			demo: 'Demo',
			source: 'Source',
			indev: `Currently in development!`,
			talktome: `Contact me to talk about this project!`,
		},
		main: {
			project: {
				1: {
					id: `project-1`,
					year: 2024,
					name: `Ball Battle`,
					desc: `A basketball prediction and social networking application. A basketball prediction and social networking application. A basketball prediction and social networking application`,
					demourl: `https://markmelnik.com`,
					sourceurl: ``,
					imagedesc: `Screenshot of ball battle project page`,
					linkdesc: `Visit my ball battle site`,
				},
				2: {
					id: `project-2`,
					year: 2023,
					name: `Fit Finder`,
					desc: `Looking for a new workout spot? Find it with FitFinder! This project was a tremendous learning experience from start to finish. The resulting solution is the product of many design choices and technical implementations on both the frontend and backend.`,
					demourl: `https://fitfinder.app`,
					sourceurl: ``,
					imagedesc: `Screenshot of fit finder project page`,
					linkdesc: `Visit my fit finder site`,
				},
				3: {
					id: `project-3`,
					year: 2023,
					name: `Portfolio | markmelnik.com`,
					desc: `Hey, you're on this site right now! I designed it to be simple yet elegant. I utilized the Intersection Observer API to create the dynamic navbar and scroll into view transitions. Let me know what you think!`,
					demourl: `https://markmelnik.com`,
					sourceurl: `https://github.com/markymelnik/personal-site`,
					imagedesc: `Screenshot of portfolio project page`,
					linkdesc: `Visit my portfolio site`,
				},
				4: {
					id: `project-4`,
					year: 2023,
					name: `Battleship`,
					desc: `A game of Battleship played in the web browser. This solution is written in vanilla JavaScript, HTML, and CSS. I underwent a test-driven development process using the Jest testing library to see this project to completion.`,
					demourl: `https://battleship.markmelnik.com`,
					sourceurl: `https://github.com/markymelnik/battleship`,
					imagedesc: `Screenshot of battleship project page`,
					linkdesc: `Visit my battleship site`,
				},
			},
			label: 'Work In Progress!',
		},
		side: {
			button: 'See More',
			header: `Some smaller projects I built along the way`,
			project: {
				5: {
					id: `project-5`,
					year: 2023,
					name: `Shopping Cart`,
					desc: `A mock shopping site with dynamic cart functionality. Great practice with React.`,
					demourl: `https://shopping-cart.markmelnik.com`,
					sourceurl: `https://github.com/markymelnik/shopping-cart`,
				},
				6: {
					id: `project-6`,
					year: 2023,
					name: `Memory Cards`,
					desc: `Test your memory with this memory game. Don't click the same cat twice 🐱.`,
					demourl: `https://memory-cards.markmelnik.com`,
					sourceurl: `https://github.com/markymelnik/memory-cards`,
				},
				7: {
					id: `project-7`,
					year: 2023,
					name: `Tic-Tac-Toe`,
					desc: `A classic game of tic-tac-toe. Have a friend with you or you'll be playing against yourself!`,
					demourl: `https://tic-tac-toe.markmelnik.com`,
					sourceurl: `https://github.com/markymelnik/tic-tac-toe`,
				},
				8: {
					id: `project-8`,
					year: 2022,
					name: `Etch-A-Sketch`,
					desc: `A drawing tool with grid size and color sliders. Great practice with event handlers.`,
					demourl: `https://etch-a-sketch.markmelnik.com`,
					sourceurl: `https://github.com/markymelnik/etch-a-sketch`,
				},
				9: {
					id: `project-9`,
					year: 2022,
					name: `Calculator`,
					desc: `Your standard 4 function calculator. This was one of my initial projects while learning basics.`,
					demourl: `https://calculator.markmelnik.com`,
					sourceurl: `https://calculator.markmelnik.com`,
				},
				10: {
					id: `project-10`,
					year: 2022,
					name: `Café Page`,
					desc: `A simple café site. Great practice with built-in page navigation and UI.`,
					demourl: `https://cafe-page.markmelnik.com`,
					sourceurl: `https://github.com/markymelnik/cafe-page`,
				}
			},
		},
	},
	contact: {
		title: 'Contact',
		header: 'Contact Me',
		number: '.03',
		p1: `Feel free to reach out! `,
		p2: `I am currently seeking an entry-level software development role.`,
	},
}